Vagrant.configure(2) do |config|
    vagrant_startx = "#{ENV['vagrant_startx']}"

  if Vagrant.has_plugin?("vagrant-proxyconf")
	puts "Vagrant proxy plugin found ..."
	if ENV["http_proxy"]
	  puts "http_proxy: " + ENV["http_proxy"]
	  config.proxy.http     = ENV["http_proxy"]
	end
	if ENV["https_proxy"]
	  puts "https_proxy: " + ENV["https_proxy"]
	  config.proxy.https    = ENV["https_proxy"]
	end
	if ENV["no_proxy"]
	  config.proxy.no_proxy = ENV["no_proxy"]
	end
  end

    config.vm.box = "ubuntu/vivid64"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", guest: 80, host: 83

    # @todo set fixed http_proxy / https_proxy in ~/.bashrc

    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--pae", "on"]
        vb.customize ["modifyvm", :id, "--chipset", "ich9"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end
end
